spring.config.import=optional:file:.env[.properties]

spring.application.name=transaction-service
server.port=8089

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

#HEALTH MONITORING - ACTUATOR
management.endpoints.web.exposure.include=health, metric, info

#EUREKA Discover
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#KAFKA CONFIGURATION
spring.kafka.bootstrap-servers=localhost:9092

#PRODUCER CONFIGURATION
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type=true

#JWT SECURITY CONFIG
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

